version: '3.8'

services:
  backend:
    build: ./backend
    container_name: azure_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: ./frontend
    container_name: azure_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
